### ISSUE TITLE
store_item should take StorageItem by reference

### ISSUE THREAD

**Issue by t-moe** [tweedegolf/sequential-storage#21]
[`store_item`](https://docs.rs/sequential-storage/latest/sequential_storage/map/fn.store_item.html) takes the StorageItem by value, even though it is only passed by reference to [`StorageItem::serialize_into`](https://docs.rs/sequential-storage/latest/sequential_storage/map/trait.StorageItem.html#tymethod.serialize_into). 

Is this an oversight or is there a bigger idea behind this?

(my StorageItem is rather big and expensiv to Clone. I would prefer to be able to continue using it, after storing it)

**Comment by diondokter** [comment]
Oh, there's no idea behind it. Wouldn't call it an oversight though, it just never came up as a problem.

We could change it. Seems fair. Are you willing to make a PR?
If you do, also include it as a breaking change in the changelog.

Since it's a breaking change, I probably don't want to release it until #19 is ready.
